### ISSUE TITLE
Error when calling cli

### ISSUE THREAD

**Issue by extranjero** [avz/jl-sql#3]
When calling cli with cmd jl-sql always getting exception 

`abdullo@abdullo-Lenovo-G510:~/$ jl-sql 
/usr/lib/node_modules/jl-sql/src/Cli.js:157
	throwUsage(code = 255)
	                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/jl-sql/src/main.js:6:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)` 

**Operating System**
Ubuntu 16.04

**Node version**
v4.4.0

**Npm version**
{ npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.0',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }

**Comment by avz** [comment]
> Node version
> v4.4.0

Unfortunately, node v6 required to run `jl-sql`

**Comment by avz** [comment]
I think, I can fix it. It will take some time.

**Comment by avz** [comment]
I release a new version (`v1.2.7`) which has an experimental support of node v4 and v5

**Comment by extranjero** [comment]
Thanks a lot
